packages:
  - packages/tool-form
  - packages/args
  - packages/markdown
  - packages/multipart
  - examples

catalogs:
  dep:
    tool-json: ^0.1.0
    tool-query: ^0.1.0
    tool-schema: ^0.1.0
    tool-uri: ^0.1.0
  dev:
    "@anthropic-ai/sdk": ^0.38.0
    "@eslint/js": ^9.21.0
    "@types/node": ^22.13.0
    eslint: ^9.21.0
    eslint-plugin-jsdoc: ^50.6.0
    openai: ^4.86
    prettier: ^3.5.0
    rimraf: ^6.0.0
    typedoc: ^0.27.0
    typescript: ^5.7.0
    typescript-eslint: ^8.25.0
